openapi: 3.0.0
info:
  title: NEST SERVICE
  version: '0.1'
paths:
  /health:
    get:
      operationId: api.health
      responses:
        default:
          description: health response

  /nested_json:
    post:
      operationId: api.nest
      parameters:
        - in: query
          name: keys
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/input_json'
              required:
                - input_json

      responses:
        200:
          description: Nested JSON
          content:
            application/json:
              schema:
                type: object

        401:
          $ref: '#/components/responses/UnauthorizedError'

      security:
      - basicAuth: []



components:
  schemas:
    input_json:
      type: array
      minItems: 1
      items:
        type: object

  securitySchemes:
    basicAuth:
        type: http
        scheme: basic
        x-basicInfoFunc: api.basic_auth

  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string




